baseURL = "https://biagg.io/"
languageCode = "en-us"
title = "Biagg.io"

[params]
  author = "Biaggio Luciano"
  description = "Personal blog by Biaggio Luciano"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "One System (OS)"
    url = "/one-system/"
    weight = 2
  [[menu.main]]
    name = "Weekly Geeky"
    url = "/weekly-geeky/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
